var ajaxurl=$('#ajaxurl').val()+'/wp-admin/admin-ajax.php';var ref=document.referrer;var sevisitor;var SE=new Array('web.info.com','search.','del.icio.us/search','soso.com','.yahoo.','/url','/search','.google.','.ask.','.baidu.','.bing.','.aol.','.answers.');for(var source in SE){var match=ref.indexOf(SE[source]);if(match!=-1){sevisitor=true;}}
$(document).ready(function(){openInBlank();var gallery=$('div[id^="gallery"]');if(gallery.length){setTimeout(function(){$('a.btnsgallery.next').click();},1000);}
if(typeof abp!=='undefined'){console.log("a:"+abp);if(abp){console.log("a:"+abp);$("#googlers").remove();$(".abp").each(function(){$(this).css({'display':"inline-block"});$(this).find(".adsbygoogle").css({'display':"inline-block"});(adsbygoogle=window.adsbygoogle||[]).push({});});}}
console.log("s:"+sevisitor);if(sevisitor&&!abp){var googlers=$("#googlers").detach();$('.historia p:nth-child(2)').after(googlers);var itemgooglers=$("#googlers");itemgooglers.css({'display':"inline-block"});itemgooglers.find(".adsbygoogle").css({'display':"inline-block"});$(".abp").remove();setTimeout(function(){console.log("s:entró");(adsbygoogle=window.adsbygoogle||[]).push({});},500);}
var patrocinado=$('.single-patrocinado');if(patrocinado.length){$('.postcontent a').attr('rel','nofollow');}
readCustomUrl();});function openInBlank(){$("a[href^=http]").each(function(){var excludes=['alt1040.com','hipertextual.com'];for(i=0;i<excludes.length;i++){if(this.href.indexOf(excludes[i])!=-1){return true;}}
if(this.href.indexOf(location.hostname)==-1){$(this).click(function(){return true;});$(this).attr({target:"_blank",title:"Abre en una nueva ventana"});$(this).click();}})}
function readCustomUrl(){$.ajax({type:"POST",url:ajaxurl,data:"action=ajax_customurl&tag="+getParam('tag')+"&exp="+getParam('exp'),dataType:"html",success:function(data){var contenidos=$(".wrap.contenidos");if(contenidos.length){contenidos.before(data);}else{$(".vipshared").append(data);}
setTimeout(function(){$('.flip-container').addClass("open");},50);}});}
function abreCompartir(event,donde){event.preventDefault();var url=$('#theperma').val();var title=$('#sharetitle').val();if(donde=='tw'){url="https://twitter.com/intent/tweet?url="+url+"&amp;text="+title+"&utm_source=self&utm_medium=singlenav&utm_campaign=botontw";}else{url="https://www.facebook.com/sharer/sharer.php?u="+url+"&utm_source=self&utm_medium=singlenav&utm_campaign=botonfb";}
window.open(url,'myWindow','status = 1, height = 550, width = 550, resizable = 0');ga('send','event',"compartir en single",donde,window.location.href);}